################################################################################
#          This file was automatically generated. Please do not edit.          #
################################################################################

import jpype



MetadataSource = jpype.JClass('org.geotools.metadata.sql.MetadataSource')

MetadataException = jpype.JClass('org.geotools.metadata.sql.MetadataException')